# Form implementation generated from reading ui file '.\templates\CalendarBajaWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgCalendarBaja(object):
    def setupUi(self, dlgCalendarBaja):
        dlgCalendarBaja.setObjectName("dlgCalendarBaja")
        dlgCalendarBaja.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dlgCalendarBaja.sizePolicy().hasHeightForWidth())
        dlgCalendarBaja.setSizePolicy(sizePolicy)
        dlgCalendarBaja.setMinimumSize(QtCore.QSize(400, 300))
        dlgCalendarBaja.setMaximumSize(QtCore.QSize(400, 300))
        self.calendarBaja = QtWidgets.QCalendarWidget(parent=dlgCalendarBaja)
        self.calendarBaja.setGeometry(QtCore.QRect(0, 0, 401, 301))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarBaja.sizePolicy().hasHeightForWidth())
        self.calendarBaja.setSizePolicy(sizePolicy)
        self.calendarBaja.setObjectName("calendarBaja")

        self.retranslateUi(dlgCalendarBaja)
        QtCore.QMetaObject.connectSlotsByName(dlgCalendarBaja)

    def retranslateUi(self, dlgCalendarBaja):
        _translate = QtCore.QCoreApplication.translate
        dlgCalendarBaja.setWindowTitle(_translate("dlgCalendarBaja", "Dialog"))
