# Form implementation generated from reading ui file 'ExitWindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgSalir(object):
    def setupUi(self, dlgSalir):
        dlgSalir.setObjectName("dlgSalir")
        dlgSalir.resize(400, 111)
        self.gridLayout = QtWidgets.QGridLayout(dlgSalir)
        self.gridLayout.setObjectName("gridLayout")
        self.btnSalirNo = QtWidgets.QPushButton(parent=dlgSalir)
        self.btnSalirNo.setObjectName("btnSalirNo")
        self.gridLayout.addWidget(self.btnSalirNo, 2, 0, 1, 1)
        self.btnSalirSi = QtWidgets.QPushButton(parent=dlgSalir)
        self.btnSalirSi.setObjectName("btnSalirSi")
        self.gridLayout.addWidget(self.btnSalirSi, 1, 0, 1, 1)
        self.lblSalir = QtWidgets.QLabel(parent=dlgSalir)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lblSalir.setFont(font)
        self.lblSalir.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lblSalir.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblSalir.setObjectName("lblSalir")
        self.gridLayout.addWidget(self.lblSalir, 0, 0, 1, 1)

        self.retranslateUi(dlgSalir)
        QtCore.QMetaObject.connectSlotsByName(dlgSalir)

    def retranslateUi(self, dlgSalir):
        _translate = QtCore.QCoreApplication.translate
        dlgSalir.setWindowTitle(_translate("dlgSalir", "Dialog"))
        self.btnSalirNo.setText(_translate("dlgSalir", "CANCELAR"))
        self.btnSalirSi.setText(_translate("dlgSalir", "ACEPTAR"))
        self.lblSalir.setText(_translate("dlgSalir", "¿DESEAS SALIR?"))
