# Form implementation generated from reading ui file '.\templates\ExitWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgSalir(object):
    def setupUi(self, dlgSalir):
        dlgSalir.setObjectName("dlgSalir")
        dlgSalir.resize(350, 250)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(130)
        sizePolicy.setHeightForWidth(dlgSalir.sizePolicy().hasHeightForWidth())
        dlgSalir.setSizePolicy(sizePolicy)
        dlgSalir.setMinimumSize(QtCore.QSize(350, 250))
        dlgSalir.setMaximumSize(QtCore.QSize(350, 250))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/a22braisdr/.designer/backup/img/driver.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        dlgSalir.setWindowIcon(icon)
        self.btnSalirNo = QtWidgets.QPushButton(parent=dlgSalir)
        self.btnSalirNo.setGeometry(QtCore.QRect(230, 190, 75, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSalirNo.sizePolicy().hasHeightForWidth())
        self.btnSalirNo.setSizePolicy(sizePolicy)
        self.btnSalirNo.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btnSalirNo.setObjectName("btnSalirNo")
        self.btnSalirSi = QtWidgets.QPushButton(parent=dlgSalir)
        self.btnSalirSi.setGeometry(QtCore.QRect(70, 190, 75, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSalirSi.sizePolicy().hasHeightForWidth())
        self.btnSalirSi.setSizePolicy(sizePolicy)
        self.btnSalirSi.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btnSalirSi.setObjectName("btnSalirSi")
        self.lblSalir = QtWidgets.QLabel(parent=dlgSalir)
        self.lblSalir.setGeometry(QtCore.QRect(80, 130, 203, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSalir.sizePolicy().hasHeightForWidth())
        self.lblSalir.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lblSalir.setFont(font)
        self.lblSalir.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lblSalir.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblSalir.setObjectName("lblSalir")
        self.label = QtWidgets.QLabel(parent=dlgSalir)
        self.label.setGeometry(QtCore.QRect(140, 20, 81, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(".\\templates\\../img/driver.ico"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(dlgSalir)
        QtCore.QMetaObject.connectSlotsByName(dlgSalir)

    def retranslateUi(self, dlgSalir):
        _translate = QtCore.QCoreApplication.translate
        dlgSalir.setWindowTitle(_translate("dlgSalir", "Dialog"))
        self.btnSalirNo.setText(_translate("dlgSalir", "CANCELAR"))
        self.btnSalirSi.setText(_translate("dlgSalir", "ACEPTAR"))
        self.lblSalir.setText(_translate("dlgSalir", "¿DESEAS SALIR?"))
